# Generated by Django 6.0.3 on 2026-03-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_user_managers_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
