# Generated by Django 6.0.3 on 2026-03-28 14:35

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_user_is_flagged'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', events.models.UserSoftDeleteManager()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='certificates_released',
            field=models.BooleanField(default=False, help_text='Whether certificates are available for download'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google OAuth ID', max_length=255, null=True, unique=True),
        ),
    ]
