# Generated by Django 6.0.3 on 2026-03-28 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_user_managers_event_certificates_released_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True, help_text='Partner logo URL')),
                ('website_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('signature_url', models.URLField(blank=True, help_text='Optional digital signature image')),
            ],
            options={
                'verbose_name_plural': 'Signatories',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.partner'),
        ),
        migrations.AddField(
            model_name='event',
            name='signatory_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.signatory'),
        ),
        migrations.AddField(
            model_name='event',
            name='signatory_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.signatory'),
        ),
        migrations.AddField(
            model_name='event',
            name='signatory_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.signatory'),
        ),
    ]
