# Generated by Django 6.0.3 on 2026-03-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_partner_signatory_event_partners_event_signatory_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='signatory',
            name='signature_url',
        ),
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, help_text='Partner logo image', null=True, upload_to='partners/'),
        ),
        migrations.AddField(
            model_name='signatory',
            name='signature',
            field=models.ImageField(blank=True, help_text='Digital signature image', null=True, upload_to='signatures/'),
        ),
    ]
