# Generated by Django 6.0.3 on 2026-03-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_uuid_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='signatories',
            field=models.ManyToManyField(blank=True, related_name='events_signatories', to='events.signatory'),
        ),
    ]
