# Generated by Django 6.0.3 on 2026-03-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_signatories'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='White Label', max_length=100)),
                ('tagline', models.CharField(default='Events', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#2962FF', help_text='Hex color for primary theme', max_length=7)),
                ('accent_color', models.CharField(default='#F58220', help_text='Hex color for secondary theme', max_length=7)),
                ('company_name', models.CharField(default='White Label Corp', max_length=255)),
                ('email', models.EmailField(default='contact@example.com', max_length=254)),
                ('website', models.CharField(default='EXAMPLE.COM', max_length=255)),
                ('hashtag', models.CharField(default='#EVENTS2026', max_length=50)),
            ],
        ),
    ]
