# Generated by Django 6.0.3 on 2026-04-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_brandingconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrence_day_of_month',
            field=models.PositiveIntegerField(blank=True, help_text='1-31', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_day_of_week',
            field=models.PositiveIntegerField(blank=True, help_text='0=Monday, 6=Sunday', null=True),
        ),
    ]
