# Generated by Django 6.0.3 on 2026-04-07 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_recurrence_day_of_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='buddy_group_size',
            field=models.PositiveIntegerField(default=5, help_text='Number of people per buddy group'),
        ),
        migrations.CreateModel(
            name='BuddyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_groups', to='events.event')),
            ],
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='buddy_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='events.buddygroup'),
        ),
    ]
