# Generated by Django 6.0.3 on 2026-04-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_buddy_group_size_buddygroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingconfiguration',
            name='description',
            field=models.TextField(default='Empowering creators to discover, compete, and connect through world-class events.', help_text='Platform description for the landing page'),
        ),
    ]
