# Generated by Django 6.0.3 on 2026-04-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_brandingconfiguration_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandingconfiguration',
            name='accent_color',
            field=models.CharField(blank=True, default='#F58220', help_text='Hex color for secondary theme', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='brandingconfiguration',
            name='company_name',
            field=models.CharField(blank=True, default='MetToday', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brandingconfiguration',
            name='description',
            field=models.TextField(blank=True, default='Empowering creators to discover, compete, and connect through world-class events.', help_text='Platform description for the landing page', null=True),
        ),
        migrations.AlterField(
            model_name='brandingconfiguration',
            name='email',
            field=models.EmailField(blank=True, default='contact@example.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='brandingconfiguration',
            name='hashtag',
            field=models.CharField(blank=True, default='#EVENTS2026', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='brandingconfiguration',
            name='name',
            field=models.CharField(blank=True, default='MetToday', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brandingconfiguration',
            name='primary_color',
            field=models.CharField(blank=True, default='#2962FF', help_text='Hex color for primary theme', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='brandingconfiguration',
            name='tagline',
            field=models.CharField(blank=True, default='Events', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brandingconfiguration',
            name='website',
            field=models.CharField(blank=True, default='EXAMPLE.COM', max_length=255, null=True),
        ),
    ]
