# Generated by Django 6.0.3 on 2026-04-08 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_brandingconfiguration_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='peer_judging_percent',
            field=models.PositiveIntegerField(default=0, help_text='Percentage of the final score contributed by peer judging (0-100)'),
        ),
        migrations.AddField(
            model_name='score',
            name='is_peer_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_given', to=settings.AUTH_USER_MODEL),
        ),
    ]
