# Generated by Django 5.2.7 on 2025-11-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
